name: Lint, Format and Deploy to AWS S3
on:
  push:
    branches:
      - development

jobs:
  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: yarn install
      - name: Prettier
        run: yarn prettify
      - name: Linter
        run: yarn eslint ./src

  deploy:
    needs: lint-and-format
    name: Deploy to AWS S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Build React App
        env:
          REACT_APP_API_URI: ${{ secrets.API_URI }}
        run: yarn install --production && yarn build
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./build/ s3://votainformado-staging --delete
